### PR TITLE
Fix: reading blog causes mobile connection to drop

### PR DESCRIPTION
**Pull request by thaJeztah**
After reading the blogs posts "How to Route Traffic through a
Tor Docker container" and "Using an R Container for Analytical
Models", the data connection on some mobile phones dropped, and
could only be resolved by contacting the telecom provider.

This change reduces the chance that this is happening by
(up to) 99.0%.

(In other words: optimized images, reducing their size from 17 MB to 164kb)

screen shot 2015-08-21 at 18 14 09

ping @jfrazelle :smile:

### CODE REVIEW

**Comment by jessfraz** [comment]
awesome!!!!

**Comment by thaJeztah** [comment]
yeah, I wondered why it took so long to clone the repo LOL. I could resize them to be smaller, but decided to keep em as-is for now :-)

**Comment by jessfraz** [comment]
you rule!

On Fri, Aug 21, 2015 at 10:48 AM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> yeah, I wondered why it took so long to clone the repo LOL. I could resize
> them to be smaller, but decided to keep em as-is for now :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jfrazelle/blog/pull/5#issuecomment-133510125.

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by jessfraz** [comment]
this is way better

On Fri, Aug 21, 2015 at 10:49 AM, Jessica Frazelle me@jessfraz.com wrote:

> you rule!
> 
> On Fri, Aug 21, 2015 at 10:48 AM, Sebastiaan van Stijn <
> notifications@github.com> wrote:
> 
> > yeah, I wondered why it took so long to clone the repo LOL. I could
> > resize them to be smaller, but decided to keep em as-is for now :-)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jfrazelle/blog/pull/5#issuecomment-133510125.
> 
> ## 
> 
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Pull request merged**
