### PR TITLE
Update blog post to be markdown friendly :)

### PR DESCRIPTION
**Pull request by marcosnils**
@jfrazelle check out if this renders correctly

### CODE REVIEW

**Comment by jessfraz** [comment]
Omg thanks

**Comment by jessfraz** [comment]
Not near a computer to test but yolo I trust you and automatic deploys ftw

**Comment by jessfraz** [comment]
Omg holy crap you're my hero

**Comment by marcosnils** [comment]
<3

**Comment by marcosnils** [comment]
I understand the feeling as OSS maintainer. This post `needs` to be right in every aspect.

**Pull request merged**
